---

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - kvm
    - qemu-kvm
    - libvirt-bin
    - virtinst

- name: Create some dirs
  file: path={{ item }} state=directory
  with_items:
    - /var/lib/libvirt/isos
    - /var/lib/libvirt/configs
